use std::path::Path;

use crate::Prefer;

use super::GeneratedFile;

pub fn generate(
    root: &Path,
    claude_md_content: Option<&str>,
    prefer: Prefer,
) -> Vec<GeneratedFile> {
    // When AGENTS.md is the source of truth, Codex reads it directly — don't clobber it.
    if prefer == Prefer::Agents {
        return Vec::new();
    }

    let Some(content) = claude_md_content else {
        return Vec::new();
    };

    let path = root.join("AGENTS.md");
    let output = format!("<!-- Generated by agentic-sync — do not edit manually -->\n\n{content}");

    vec![GeneratedFile {
        path,
        content: output,
    }]
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn generates_agents_md() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();

        let content = "# Project\n\nUse Rust.";
        let files = generate(root, Some(content), Prefer::Claude);

        assert_eq!(files.len(), 1);
        assert_eq!(files[0].path, root.join("AGENTS.md"));
        assert!(
            files[0]
                .content
                .starts_with("<!-- Generated by agentic-sync")
        );
        assert!(files[0].content.contains(content));
    }

    #[test]
    fn no_claude_md_no_output() {
        let dir = TempDir::new().unwrap();
        let files = generate(dir.path(), None, Prefer::Claude);
        assert!(files.is_empty());
    }

    #[test]
    fn prefer_agents_skips_generation() {
        let dir = TempDir::new().unwrap();
        let files = generate(dir.path(), Some("# Project"), Prefer::Agents);
        assert!(files.is_empty());
    }
}
