use std::path::Path;

use super::GeneratedFile;

pub fn generate(root: &Path, claude_md_content: Option<&str>) -> Vec<GeneratedFile> {
    let Some(content) = claude_md_content else {
        return Vec::new();
    };

    let path = root.join(".github/copilot-instructions.md");
    let output = format!("<!-- Generated by agentic-sync — do not edit manually -->\n\n{content}");

    vec![GeneratedFile {
        path,
        content: output,
    }]
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn generates_copilot_instructions() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();

        let content = "# Project\n\nUse Rust for everything.";
        let files = generate(root, Some(content));

        assert_eq!(files.len(), 1);
        assert_eq!(files[0].path, root.join(".github/copilot-instructions.md"));
        assert!(
            files[0]
                .content
                .starts_with("<!-- Generated by agentic-sync")
        );
        assert!(files[0].content.contains(content));
    }

    #[test]
    fn no_claude_md_no_output() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();

        let files = generate(root, None);
        assert!(files.is_empty());
    }
}
