use std::fs;

#[test]
fn fix_generates_all_target_files() {
    let dir = tempfile::tempdir().unwrap();
    super::setup_full_project(dir.path());
    let result = agentic_sync::run(
        dir.path(),
        agentic_sync::Mode::Fix { overwrite: false },
        &agentic_sync::all_targets(),
    )
    .unwrap();
    assert_eq!(result, std::process::ExitCode::SUCCESS);

    assert!(dir.path().join(".cursor/rules/_project.mdc").exists());
    assert!(dir.path().join(".cursor/rules/stack.mdc").exists());
    assert!(dir.path().join(".cursor/rules/testing.mdc").exists());
    assert!(dir.path().join(".cursor/rules/style.mdc").exists());
    assert!(dir.path().join(".cursor/skills/explain-code.mdc").exists());

    let mcp = fs::read_to_string(dir.path().join(".cursor/mcp.json")).unwrap();
    assert!(mcp.contains("mcpServers"));

    let copilot = fs::read_to_string(dir.path().join(".github/copilot-instructions.md")).unwrap();
    assert!(copilot.contains("Generated by agentic-sync"));
    assert!(copilot.contains("## Stack"));
}

#[test]
fn fix_with_target_filter() {
    let dir = tempfile::tempdir().unwrap();
    super::setup_basic_project(dir.path());
    agentic_sync::run(
        dir.path(),
        agentic_sync::Mode::Fix { overwrite: false },
        &[agentic_sync::Target::Cursor],
    )
    .unwrap();
    assert!(dir.path().join(".cursor/rules/stack.mdc").exists());
    assert!(!dir.path().join(".github/copilot-instructions.md").exists());
}
