use std::path::{Path, PathBuf};

use crate::generate::GeneratedFile;

const GENERATED_BY_MARKER: &str = "generated-by: agentic-sync";
const GENERATED_BY_HTML_MARKER: &str = "<!-- Generated by agentic-sync";

#[derive(Debug, Default)]
pub struct OutputResult {
    pub stale: Vec<PathBuf>,
    pub written: Vec<PathBuf>,
    pub skipped: Vec<PathBuf>,
    pub deleted: Vec<PathBuf>,
    pub warnings: Vec<String>,
}

impl OutputResult {
    pub fn is_in_sync(&self) -> bool {
        self.stale.is_empty() && self.skipped.is_empty()
    }
}

pub fn check(files: &[GeneratedFile]) -> OutputResult {
    let mut result = OutputResult::default();

    for file in files {
        if !file.path.exists() {
            result.stale.push(file.path.clone());
            continue;
        }

        let existing = match std::fs::read_to_string(&file.path) {
            Ok(s) => s,
            Err(_) => {
                result.stale.push(file.path.clone());
                continue;
            }
        };

        if existing == file.content {
            // In sync — nothing to do
            continue;
        }

        if has_generated_by_marker(&file.path) {
            result.stale.push(file.path.clone());
        } else {
            result.warnings.push(format!(
                "{}: file exists without generated-by marker, skipping",
                file.path.display()
            ));
            result.skipped.push(file.path.clone());
        }
    }

    result
}

pub fn fix(files: &[GeneratedFile], overwrite: bool) -> OutputResult {
    let mut result = OutputResult::default();

    for file in files {
        if file.path.exists() && !overwrite && !has_generated_by_marker(&file.path) {
            crate::log::warn_file(&file.path, "skipped (no generated-by marker)");
            result.skipped.push(file.path.clone());
            continue;
        }

        if let Some(parent) = file.path.parent()
            && !parent.exists()
            && let Err(e) = std::fs::create_dir_all(parent)
        {
            crate::log::error_file(&file.path, &format!("failed to create directory: {e}"));
            continue;
        }

        match std::fs::write(&file.path, &file.content) {
            Ok(()) => {
                result.written.push(file.path.clone());
            }
            Err(e) => {
                crate::log::error_file(&file.path, &format!("failed to write: {e}"));
            }
        }
    }

    result
}

pub fn cleanup(root: &Path, current_files: &[GeneratedFile]) -> Vec<PathBuf> {
    let mut deleted = Vec::new();
    let dirs = [root.join(".cursor/rules"), root.join(".cursor/skills")];

    for dir in &dirs {
        if !dir.is_dir() {
            continue;
        }
        let entries = match std::fs::read_dir(dir) {
            Ok(e) => e,
            Err(_) => continue,
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if !path.is_file() {
                continue;
            }
            // Skip if it's in the current generated set
            if current_files.iter().any(|f| f.path == path) {
                continue;
            }
            // Only delete if it has the generated-by marker
            if has_generated_by_marker(&path) && std::fs::remove_file(&path).is_ok() {
                deleted.push(path);
            }
        }
    }

    deleted
}

fn has_generated_by_marker(path: &Path) -> bool {
    match std::fs::read_to_string(path) {
        Ok(content) => {
            content.contains(GENERATED_BY_MARKER) || content.contains(GENERATED_BY_HTML_MARKER)
        }
        Err(_) => false,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::TempDir;

    #[test]
    fn check_detects_stale_file() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join(".cursor/rules/test.mdc");
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(
            &path,
            "---\ngenerated-by: agentic-sync\nalwaysApply: true\n---\n\nOld content.\n",
        )
        .unwrap();

        let files = vec![GeneratedFile {
            path: path.clone(),
            content: "---\ngenerated-by: agentic-sync\nalwaysApply: true\n---\n\nNew content.\n"
                .to_string(),
        }];

        let result = check(&files);
        assert_eq!(result.stale.len(), 1);
        assert_eq!(result.stale[0], path);
        assert!(!result.is_in_sync());
    }

    #[test]
    fn check_reports_in_sync() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join(".cursor/rules/test.mdc");
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        let content = "---\ngenerated-by: agentic-sync\nalwaysApply: true\n---\n\nSame content.\n";
        fs::write(&path, content).unwrap();

        let files = vec![GeneratedFile {
            path: path.clone(),
            content: content.to_string(),
        }];

        let result = check(&files);
        assert!(result.stale.is_empty());
        assert!(result.skipped.is_empty());
        assert!(result.is_in_sync());
    }

    #[test]
    fn check_new_file_is_stale() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join(".cursor/rules/new.mdc");

        let files = vec![GeneratedFile {
            path: path.clone(),
            content: "new content".to_string(),
        }];

        let result = check(&files);
        assert_eq!(result.stale.len(), 1);
        assert_eq!(result.stale[0], path);
        assert!(!result.is_in_sync());
    }

    #[test]
    fn fix_writes_new_files() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join(".cursor/rules/new.mdc");

        let files = vec![GeneratedFile {
            path: path.clone(),
            content: "---\ngenerated-by: agentic-sync\n---\n\nContent.\n".to_string(),
        }];

        let result = fix(&files, false);
        assert_eq!(result.written.len(), 1);
        assert_eq!(result.written[0], path);
        assert!(path.exists());
        assert_eq!(
            fs::read_to_string(&path).unwrap(),
            "---\ngenerated-by: agentic-sync\n---\n\nContent.\n"
        );
    }

    #[test]
    fn fix_skips_unowned_file() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join(".cursor/rules/manual.mdc");
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        let original = "Manual content without marker.";
        fs::write(&path, original).unwrap();

        let files = vec![GeneratedFile {
            path: path.clone(),
            content: "---\ngenerated-by: agentic-sync\n---\n\nNew.\n".to_string(),
        }];

        let result = fix(&files, false);
        assert_eq!(result.skipped.len(), 1);
        assert!(result.written.is_empty());
        // Original content preserved
        assert_eq!(fs::read_to_string(&path).unwrap(), original);
    }

    #[test]
    fn fix_overwrites_unowned_when_forced() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join(".cursor/rules/manual.mdc");
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(&path, "Manual content without marker.").unwrap();

        let new_content = "---\ngenerated-by: agentic-sync\n---\n\nNew.\n".to_string();
        let files = vec![GeneratedFile {
            path: path.clone(),
            content: new_content.clone(),
        }];

        let result = fix(&files, true);
        assert_eq!(result.written.len(), 1);
        assert!(result.skipped.is_empty());
        assert_eq!(fs::read_to_string(&path).unwrap(), new_content);
    }

    #[test]
    fn cleanup_deletes_stale_generated_files() {
        let dir = TempDir::new().unwrap();
        let root = dir.path();

        let rules_dir = root.join(".cursor/rules");
        fs::create_dir_all(&rules_dir).unwrap();

        // A stale generated file (not in current set)
        let stale_path = rules_dir.join("old.mdc");
        fs::write(
            &stale_path,
            "---\ngenerated-by: agentic-sync\n---\n\nOld.\n",
        )
        .unwrap();

        // A manual file (should be preserved)
        let manual_path = rules_dir.join("manual.mdc");
        fs::write(&manual_path, "Manual rules.").unwrap();

        // A current generated file (should be preserved)
        let current_path = rules_dir.join("current.mdc");
        fs::write(
            &current_path,
            "---\ngenerated-by: agentic-sync\n---\n\nCurrent.\n",
        )
        .unwrap();

        let current_files = vec![GeneratedFile {
            path: current_path.clone(),
            content: "---\ngenerated-by: agentic-sync\n---\n\nCurrent.\n".to_string(),
        }];

        let deleted = cleanup(root, &current_files);

        assert_eq!(deleted.len(), 1);
        assert_eq!(deleted[0], stale_path);
        assert!(!stale_path.exists());
        assert!(manual_path.exists());
        assert!(current_path.exists());
    }
}
